<template lang="html">
  <div v-b-modal.modal1 class="">
    <b-card v-bind:title="title">
      <b-card v-if="tasks && tasks.length>0" v-for="task in tasks" :bg-variant="cardColors"
             :header="task.title"
             class="task mb-2"
             text-variant="white">
         <p class="card-text">{{task.description}}</p>
         <small class="text-light" slot="footer">Assigned to: {{task.assignedTo}} <b-badge pill variant="success">{{task.point}}</b-badge></small>
     </b-card>
     <b-alert v-else show variant="info">Nothing here yet.</b-alert>
    </b-card>
  </div>
</template>

<script>
export default {
  data() {
    return {
    };
  },
  props: ['title', 'tasks'],
  computed: {
    cardColors() {
      return 'danger';
    },
  },
};
</script>

<style lang="css">
.task:hover {
  cursor: pointer;
	-webkit-animation: shadow-drop-2-center 0.2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: shadow-drop-2-center 0.2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
@-webkit-keyframes shadow-drop-2-center {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    -webkit-transform: translateZ(50px);
            transform: translateZ(50px);
    -webkit-box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
            box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
  }
}
@keyframes shadow-drop-2-center {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    -webkit-transform: translateZ(50px);
            transform: translateZ(50px);
    -webkit-box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
            box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
  }
}

/* ----------------------------------------------
 * Css Animation Generated by Animista on 2017-11-4 15:32:39
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shadow-drop-2-center
 * ----------------------------------------
 */
</style>
